-- Cover letter generated by the analysis pipeline, stored alongside the match
-- result so the history/detail overlay can offer it without an extra fetch.
-- Nullable: existing analyses (and any where generation failed) simply have none.
ALTER TABLE public.analyses
    ADD COLUMN cover_letter text;
