name: Backend Deploy

on:
  push:
    branches: [main]
    paths:
      - "scraper-job/**"
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: SSH & deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd ${{ secrets.VPS_PROJECT_PATH }}
            git pull origin main
            cd scraper-job
            docker compose -f docker-compose.prod.yml up --build -d
            docker image prune -f
